server.port=${PORT:8001}

# Variables de entorno del hosting
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# En prod: validate evita que Hibernate modifique la BD por accidente
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false