spring.application.name=userservice

# Puerto
server.port=8002

# === POSTGRESQL ===
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / HIBERNATE ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# === JWT ===
jwt.secret=clave-super-secreta-larga-de-al-menos-32-caracteres
jwt.expiration=86400000