server.port=8080

# URLs locales
USER_SERVICE_URL=http://localhost:8002
PRODUCT_SERVICE_URL=http://localhost:8001

# JWT en dev (valor fijo, no necesitas variable de entorno)
jwt.secret=dev-secret-key-local-no-usar-en-produccion

# Logs más verbosos en dev
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG