spring.application.name=gatewayservice
server.port=8080

# JWT
jwt.secret=clave-super-secreta-larga-de-al-menos-32-caracteres

# USERSERVICE - rutas públicas, sin filtro JWT
spring.cloud.gateway.server.webflux.routes[0].id=userservice
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8002
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# PRODUCTSERVICE - GETs públicos
spring.cloud.gateway.server.webflux.routes[1].id=productservice-public
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8001
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**,/categories/**,/brands/**,/sizes/**, /colors/**
spring.cloud.gateway.server.webflux.routes[1].predicates[1]=Method=GET
# Sin filtro JWT

# PRODUCTSERVICE - POST/PUT/DELETE protegidos
spring.cloud.gateway.server.webflux.routes[2].id=productservice-protected
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8001
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[2].predicates[1]=Method=POST,PUT,DELETE
spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthFilter

# UPLOADS - siempre público
spring.cloud.gateway.server.webflux.routes[3].id=productservice-uploads
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8001
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/uploads/**