server.port=${PORT:8080}

# URLs vienen de variables de entorno (Render, Railway, etc.)
USER_SERVICE_URL=${USER_SERVICE_URL}
PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL}

# Logs mínimos en prod
logging.level.root=WARN
logging.level.com.tuempresa=INFO